### ISSUE TITLE
Code Review from the standup team 155

### ISSUE THREAD

**Issue by jcy2704** [marcelomaidden/newyorktimes_microverse#2]
Try to center your sections better. Experiment with other ways to center the content.
Eliminate the horizontal scrollbar, its caused because of the more articles section

**Comment by carloso0114** [comment]
Good job, looks great, try to fix the horizontal scrollbar thats maging the page bigger than it should.

**Comment by StarSheriff2** [comment]
it looks great. I think the main thing is to center all the content correctly to get rid of the horizontal bar. Check with the inspection tool to find which element makes your content "stretch" out of bounds.
Try to find what is breaking your grid images on the live version. Try using the figure element as an alternative for this.
