### ISSUE TITLE
Code Review from team 155 

### ISSUE THREAD

**Issue by jcy2704** [marcelomaidden/newyorktimes_microverse#3]

**Comment by StarSheriff2** [comment]
No comments. You have made all the suggested changes to the project.

**Comment by carloso0114** [comment]
The code looks great was properly finished, maybe an optional sugestion is adding some hover effect into this part 
![image](https://user-images.githubusercontent.com/14119855/94279261-7c1ca380-ff11-11ea-9c48-df6dda1b7c36.png)
So it would looks like this but its optional.
![image](https://user-images.githubusercontent.com/14119855/94279298-850d7500-ff11-11ea-9aba-a1dff8f22b7a.png)

**Comment by marcelomaidden** [comment]
> The code looks great was properly finished, maybe an optional sugestion is adding some hover effect into this part
> ![image](https://user-images.githubusercontent.com/14119855/94279261-7c1ca380-ff11-11ea-9c48-df6dda1b7c36.png)
> So it would looks like this but its optional.
> ![image](https://user-images.githubusercontent.com/14119855/94279298-850d7500-ff11-11ea-9aba-a1dff8f22b7a.png)

Thanks for the suggestion Carlos. We fixed this on our last commit.
